config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/tasks", to: "tasks#index", as: :tasks
  get '/tasks/new', to: 'tasks#new' #render the form
  get "/tasks/:id", to: "tasks#show", as: :task
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task # mostrar o form pro usario
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # para poder render the form
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to list", tasks_path%>

app/views/tasks/index.html.erb
<h1>My tasks</h1>


<% @tasks.each do |task| %>
  <% if task.completed %>
    <p><%= link_to "(X) #{task.title}", task_path(task) %></p>
  <% else %>
    <p><%= link_to "( ) #{task.title}", task_path(task) %></p>
  <% end %>
<% end %>

<div class="btn"><%= link_to "Create Task", tasks_new_path%></div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to list", tasks_path%>

app/views/tasks/show.html.erb
<h1>New Task</h1>
<h1><%= @task.title %></h1>
<h2><%= @task.details %> </h2>
<% if @task.completed %>
  <p><%= "This task is completed" %></p>
<% else %>
  <p><%= "This task is not completed yet" %></p>
<% end %>


<%= link_to "Edit this task", edit_task_path%>

<%= link_to "Back to list", tasks_path%>

<%= link_to "Delete task", delete_task_path(@task.id), method: :delete, data: {confirm: "Are you sure you want to delete this task foreeeever!?"}%>